force-app/main/default/objects/Case/fields/RS_Last_Interaction_Channel__c.field-meta.xml
<CustomField>
    <fullName>RS_Last_Interaction_Channel__c</fullName>
    <label>Last Interaction Channel</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/RS_Einstein_Sentiment_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>RS Einstein Sentiment Configuration</label>
    <pluralLabel>RS Einstein Sentiment Configurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/RS_EmailMessageTriggerHandler.cls
/**
* @description : this is RS_EmailMessageTriggerHandler class.
* @author : Accenture
* @group :
* @last modified on : 03-24-2023
* @last modified by : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class RS_EmailMessageTriggerHandler {
    /**
    * @description : This is afterInsert method.
    * @Return : void
    * @Method Name : afterInsert
    * @param em 
    **/
    public static void afterInsert(List<EmailMessage> em){
        Map<Id, Case> caseMap = new Map<Id, Case>();
        String channelname =[Select DeveloperName from RS_Einstein_Sentiment_Configuration__mdt where label='Email' WITH SECURITY_ENFORCED]?.DeveloperName;
        for(EmailMessage emailmessage: em){
            //caseMap.put(emailmessage.RelatedToId, new Case(Id=emailmessage.RelatedToId, RS_Last_Interaction_Channel__c='Email'));
            if(emailmessage.Status=='0' && emailmessage.Incoming == true){
            RS_SentimentCalculator.getSentiment(channelname,emailmessage.Id);
            }
        }
        update caseMap.values();
    }
}