force-app/main/default/objects/MessagingSession/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/Conversation_Transcript_Body__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Transcript_Body__c</fullName>
    <label>Conversation Transcript Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/RS_Einstein_Sentiment_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>RS Einstein Sentiment Configuration</label>
    <pluralLabel>RS Einstein Sentiment Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Customer_sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_sentiments__c</fullName>
    <label>Customer sentiments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Settings__mdt/RS_Einstein_Sentiment_Settings__mdt.object-meta.xml
<CustomObject>
    <label>RS Einstein Sentiment Settings</label>
    <pluralLabel>RS Einstein Sentiment Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/Sentiment_Score__c.object-meta.xml
<CustomObject>
    <label>Sentiment Score</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sentiment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Conversation_Channel__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Channel__c</fullName>
    <label>Conversation Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voice Call</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Live Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <inlineHelpText>Gives Probability of Customer Sentiment</inlineHelpText>
    <label>Sentiment Probability Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiments__c</fullName>
    <label>Customer Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Messaging_Session__c.field-meta.xml
<CustomField>
    <fullName>Messaging_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Messaging Session</label>
    <referenceTo>MessagingSession</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RS_MessagingSessionBatch.cls
/**
* @description :This batch class is used for updating Chat transcript on Messaging Records
* @author : Accenture
* @group :
* @last modified on : 04-12-2022
* @last modified by : Accenture
**/
global class RS_MessagingSessionBatch implements Database.Batchable<sObject>,Database.AllowsCallouts {
	
	global Database.QueryLocator start(Database.BatchableContext bc) { 
        
        String query = 'SELECT id, Status,CaseId, Customer_Sentiment_Score__c, Batch_Processed__c, Conversation_Transcript_Body__c, Customer_Sentiments__c from MessagingSession where CaseId!=null AND Status = \'Ended\' AND Customer_Sentiment_Score__c =null AND Batch_Processed__c = false' ;
        // retruning all MessagingSession data where Status = 'Ended' and sentiment score is not calculated
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<MessagingSession> scope) {
        
		try{
		    List<ConversationEntry> conEntry = new List<ConversationEntry>();
            Map<id,List<ConversationEntry>> mapConIdListConEntry = new Map<id,List<ConversationEntry>>();
            List<MessagingSession> msgList = new List<MessagingSession>();
            String ChannelName=[Select DeveloperName from RS_Einstein_Sentiment_Configuration__mdt where label='SMS' WITH SECURITY_ENFORCED].DeveloperName;
			RS_Einstein_Sentiment_Settings__mdt Sentisettings = RS_Einstein_Sentiment_Settings__mdt.getInstance('X1');
            List<Vision.Prediction> predictInstance;
			RS_PredictionController PredCont = new RS_PredictionController();
			String access_token = PredCont.getAccessToken();
            conEntry = [Select id, conversationId, ActorType, Message from ConversationEntry where ActorType='EndUser' and ConversationId IN:scope];
            if(conEntry.size()>0 && conEntry!=null){
            for(ConversationEntry ce: conEntry){
				if(mapConIdListConEntry.containskey(ce.conversationId)){
                	List<ConversationEntry> listConEntry = mapConIdListConEntry.get(ce.conversationId);
                    listConEntry.add(ce);
                    mapConIdListConEntry.put(ce.conversationId,listConEntry);
                }
                else{
                    mapConIdListConEntry.put(ce.conversationId,new list<ConversationEntry>{ce});
                }
			}
            for(MessagingSession msg :scope){
                if(mapConIdListConEntry.containskey(msg.id)){
                    conEntry = mapConIdListConEntry.get(msg.id);
                    msg.Conversation_Transcript_Body__c=' ';
                    if(conEntry.size()>0 && conEntry!=null){
                        for(integer i=0; i<conEntry.size(); i++){
                            msg.Conversation_Transcript_Body__c += conEntry[i].Message +' ';
                        }
                    }
                    msg.Batch_Processed__c = true;
                    //Sentiment section
                    predictInstance = new List<Vision.Prediction>();
                    predictInstance = Vision.predictSentiment(msg.Conversation_Transcript_Body__c,access_token,Sentisettings.Model__c);
                    if((!predictInstance.isempty()) && predictInstance[0].probability != null){
                            msg.Customer_Sentiment_Score__c = predictInstance[0].probability;
                        	msg.Customer_Sentiments__c = predictInstance[0].Label;
                    }
                }else{
					msg.Customer_Sentiment_Score__c =0.5;
				}
				msgList.add(msg);
       		}
            Database.update(msgList, false);
                list<Sentiment_Score__c> listSenticoreSMS = new list<Sentiment_Score__c>();
                for(messagingsession ms: msgList){
                    Sentiment_Score__c sentiObj = new Sentiment_Score__c();
                    sentiObj.Case__c = ms.CaseId;
                    sentiObj.Customer_Sentiment_Score__c = ms.Customer_Sentiment_Score__c;
                    sentiObj.Customer_Sentiments__c = ms.Customer_Sentiments__c;
                    sentiObj.Conversation_Channel__c ='SMS';
                    sentiObj.Messaging_Session__c = ms.id;
                    listSenticoreSMS.add(sentiObj);  
                }
                if(!listSenticoreSMS.isempty()){
                    database.insert(listSenticoreSMS,false);
                }
            }
		}catch(Exception e){
            system.debug('Exception Message>>>>>' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
    	System.debug('>>>> finish ' + job.Status);
    }
    
}