force-app/main/default/objects/MessagingSession/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Messaging Sessions</relationshipLabel>
    <relationshipName>Messaging_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RS_Agent_Workflow__c/RS_Agent_Workflow__c.object-meta.xml
<CustomObject>
    <label>Agent Workflow</label>
    <nameField>
        <label>Agent Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agent Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RS_Agent_Workflow__c/fields/RS_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>RS_Action_Name__c</fullName>
    <label>Action Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Agent_Workflow__c/fields/Text_Field_To_Update__c.field-meta.xml
<CustomField>
    <fullName>Text_Field_To_Update__c</fullName>
    <label>Field To Update</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RS_Agent_Workflow_Navigation__c/RS_Agent_Workflow_Navigation__c.object-meta.xml
<CustomObject>
    <label>Agent Workflow Navigation</label>
    <nameField>
        <displayFormat>AWN-{0000}</displayFormat>
        <label>Agent Workflow Navigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Workflow Navigations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RS_Agent_Workflow_Navigation__c/fields/RS_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>RS_Action_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Name</label>
    <referenceTo>RS_Agent_Workflow__c</referenceTo>
    <relationshipLabel>Agent Workflow Navigations</relationshipLabel>
    <relationshipName>Agent_Workflow_Navigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RS_Agent_Workflow_Navigation__c/fields/RS_Parent__c.field-meta.xml
<CustomField>
    <fullName>RS_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>RS_Agent_Workflow__c</referenceTo>
    <relationshipLabel>Agent Workflow Navigations (Parent)</relationshipLabel>
    <relationshipName>Agent_Workflow_Navigations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RS_DynamicSearch__mdt/RS_DynamicSearch__mdt.object-meta.xml
<CustomObject>
    <label>RS_DynamicSearch</label>
    <pluralLabel>RS_DynamicSearch</pluralLabel>
</CustomObject>

force-app/main/default/classes/RS_AgentGuidedWorkflow_TestClass.cls
/**
 * @description       : Test Class for RS_AgentGuidedWorkflow
 * @author            : Accenture
 * @group             : 
 * @last modified on  : 03-23-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@Istest
public class RS_AgentGuidedWorkflow_TestClass {
    /**
    * @description : Test Data Setup
    * @author Accenture | 03-23-2023 
    **/
    @TestSetup
    static void testdata(){
        User us = TestDataFactory.createUser();
    }
    @IsTest
    public static void testgetAgentWorkflowWithChoices(){
        RS_Agent_Workflow__c agentWorkflowParent = TestDataFactory.createAgentWorkflowParent();
        RS_Agent_Workflow__c agentWorkflowChild1 = TestDataFactory.createAgentWorkflowChild();
        RS_Agent_Workflow_Navigation__c	 agentWorkflowNav2 = new RS_Agent_Workflow_Navigation__c();
        agentWorkflowNav2.RS_Action_Name__c=agentWorkflowChild1.id;
        agentWorkflowNav2.RS_Parent__c=agentWorkflowParent.Id;
        insert agentWorkflowNav2;
        User us = [Select id from user where LastName='Test' LIMIT 1];
        System.runAs(us){
            RS_AgentGuidedWorkflow.getAgentWorkflowWithChoices(agentWorkflowParent.RS_Action_Name__c);
            RS_AgentGuidedWorkflow.getScriptingDataForNoChildRecord(agentWorkflowParent.RS_Action_Name__c);
            RS_AgentGuidedWorkflow.getActionNumberType(agentWorkflowChild1.name);            //Contact con = Testdatafactory.conMethod(true);
            MessagingSession msobj=Testdatafactory.MsgMethod();
            Account ac = TestDataFactory.accList();
            msobj.Related_Account__c=ac.id;
            update msobj;
            LiveChatTranscript lcobj=Testdatafactory.LCList(true);
            List<String> choices = new List<String>{'1','3'};
            String success=RS_AgentGuidedWorkflow.createWorkflowChoices(choices,msobj.id,us.Id);
            RS_AgentGuidedWorkflow.createWorkflowChoices(choices,lcobj.id,us.Id);
             RS_AgentGuidedWorkflow.getRecordType(success);
            System.assertEquals(true,String.isNotEmpty(success));
        }
        
    }
    @IsTest
    public static void testAgentGuidedWorkflow(){
        RS_DynamicSearch__mdt getmetarec=[Select Object_Name__c  from RS_DynamicSearch__mdt limit 1];
        RS_Agent_Workflow__c agentWorkflowParent = TestDataFactory.createAgentWorkflowParent();
        User us = [Select id,LastName from user where LastName='Test' LIMIT 1];
        System.runAs(us){
            RS_AgentGuidedWorkflow.getWorkflowRootNode(us.Id);
            RS_AgentGuidedWorkflow.getPickListValuesIntoList(getmetarec.Object_Name__c,agentWorkflowParent.Text_Field_To_Update__c);
        }
        System.assertEquals('Test',us.LastName);
        
    }
}