force-app/main/default/objects/MessagingSession/fields/RS_Switching_Requested_Time__c.field-meta.xml
<CustomField>
    <fullName>RS_Switching_Requested_Time__c</fullName>
    <label>Switching Requested Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/RS_Switching_Status__c.field-meta.xml
<CustomField>
    <fullName>RS_Switching_Status__c</fullName>
    <label>Switching Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/RS_switchtovoice__c.field-meta.xml
<CustomField>
    <fullName>RS_switchtovoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>switch to voice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RS_SwitchToVoiceAction.cls
/**
* @description       : Controller Class for SwitchToVoice LWC
* @author            : Accenture
* @group             : 
* @last modified on  : 03-24-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class RS_SwitchToVoiceAction{
    /**
    * @description : Method to update the messaging session record to switch to voice
    * @author Accenture | 03-24-2023 
    * @param recordId 
    **/
    @AuraEnabled
    Public static void UpdateSwitchToVoice(String recordId ){
        if(Schema.getGlobalDescribe().get('MessagingSession').getDescribe().isAccessible()) {
        MessagingSession ms =[select RS_Switching_Requested_Time__c,RS_switchtovoice__c,RS_Switching_Status__c from MessagingSession where id=:recordId WITH SECURITY_ENFORCED];
        if(MessagingSession.sObjectType.getDescribe().isUpdateable()){
            ms.RS_Switching_Requested_Time__c = system.now();
            ms.RS_switchtovoice__c =True;
            ms.RS_Switching_Status__c ='Requested';
            update ms;
        }
        }
    }
    
    
    
    
}