force-app/main/default/objects/Case/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <businessProcess>Case  Support Process</businessProcess>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/VoiceCall/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/Conversation_Transcript_Body__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Transcript_Body__c</fullName>
    <label>Conversation Transcript Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/IVRIntent__c.field-meta.xml
<CustomField>
    <fullName>IVRIntent__c</fullName>
    <label>Issue Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/IVRType__c.field-meta.xml
<CustomField>
    <fullName>IVRType__c</fullName>
    <label>Customer call reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_Callback_Status__c.field-meta.xml
<CustomField>
    <fullName>RS_Callback_Status__c</fullName>
    <label>Callback Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>RequestedViaCaip</fullName>
                <label>Requested via CAIP</label>
            </value>
            <value>
                <fullName>ExtraInboundCall</fullName>
                <isActive>false</isActive>
                <label>ExtraInboundCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_ContactId__c.field-meta.xml
<CustomField>
    <fullName>RS_ContactId__c</fullName>
    <label>ContactId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_Preferred_Callback_Time__c.field-meta.xml
<CustomField>
    <fullName>RS_Preferred_Callback_Time__c</fullName>
    <label>Preferred Callback Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/RS_VoiceCallBatchTestClass.cls
@IsTest
public class RS_VoiceCallBatchTestClass {
      	 @TestSetup
    public static void createTestData(){
           case cs=TestDataFactory.csList();
        VoiceCall vc=new VoiceCall();
        vc.RS_Preferred_Callback_Time__c=DateTime.Now().addDays(1);
        vc.RS_Callback_Status__c='Requested';
        vc.IVRType__c='New Case';
        vc.VendorType ='ContactCenter';
        vc.CallType='Inbound';
        vc.ToPhoneNumber ='+18334133093';
        vc.IVRIntent__c='Billing';
        vc.FromPhoneNumber= '+16617480240';
        vc.CallStartDateTime =date.newInstance(2022, 20, 18);
        vc.CallEndDateTime = date.newInstance(2022, 20, 18);
        vc.VendorCallKey='ab1fafae-8202-4d39-a067-1082feb57c6d';
        vc.CallDisposition='completed';
        vc.RS_ContactId__c='1824b102-cf96-483a-8898-da5c5695fa37';
        vc.RelatedRecordId = cs.Id;
        vc.Customer_Sentiment_Score__c=null;
        vc.Batch_Processed__c = false;
        vc.Conversation_Transcript_Body__c='ab1fafae-8202-4d39-a067-1082feb57c6d';
        vc.Customer_Sentiments__c='Neutral';
        insert vc;
    }
    @isTest
    public static void testVoiceBatch(){
        Voicecall vc= [SELECT id,VendorCallKey, RelatedRecordId, Customer_Sentiment_Score__c,
 Batch_Processed__c, Conversation_Transcript_Body__c,
 Customer_Sentiments__c, 
 CallDisposition from VoiceCall limit 1];
        String vendorCallKey=[SELECT VendorCallKey from VoiceCall limit 1]?.VendorCallKey;
        Test.setMock(HttpCalloutMock.class, new RS_VoiceCallOutClass()); 
        
           Test.startTest();
      	RS_VoiceCallBatch.getData(vendorCallKey);
        RS_VoiceCallBatch x = new RS_VoiceCallBatch();
    	database.executeBatch(x);
    	Test.stopTest();
    }
     @isTest
    public static void testBatch(){
        RS_VoiceCallBatch obj = new RS_VoiceCallBatch();
        //Access token
        Test.setMock(HttpCalloutMock.class, new RS_HttpMockCalloutClass());
        VoiceCall msg = TestDataFactory.VCList(true);
        TestDataFactory.doclist();
        
        RS_PredictionController PredCont = new RS_PredictionController();
        String access_token = PredCont.getAccessToken();
   
        
        DataBase.executebatch(obj);         
    } 
}