force-app/main/default/objects/RS_Einstein_Sentiment_Settings__mdt/RS_Einstein_Sentiment_Settings__mdt.object-meta.xml
<CustomObject>
    <label>RS Einstein Sentiment Settings</label>
    <pluralLabel>RS Einstein Sentiment Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/Sentiment_Score__c.object-meta.xml
<CustomObject>
    <label>Sentiment Score</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sentiment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Conversation_Channel__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Channel__c</fullName>
    <label>Conversation Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voice Call</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Live Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <inlineHelpText>Gives Probability of Customer Sentiment</inlineHelpText>
    <label>Sentiment Probability Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiments__c</fullName>
    <label>Customer Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Voice_Call__c.field-meta.xml
<CustomField>
    <fullName>Voice_Call__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voice Call</label>
    <referenceTo>VoiceCall</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/Conversation_Transcript_Body__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Transcript_Body__c</fullName>
    <label>Conversation Transcript Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <label>Probability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RS_VoiceCallBatch.cls
/**
* @description       : This batch class is used for updating Chat transcript on Voice Call Records
* @author            : Accenture
* @group             : 
* @last modified on  : 02-25-2022
* @last modified by  : Accenture
**/
global class RS_VoiceCallBatch implements Database.Batchable<sObject>,Database.AllowsCallouts {
  
  global Database.QueryLocator start(Database.BatchableContext bc) { 
        
        String query = 'SELECT id,VendorCallKey, RelatedRecordId, Customer_Sentiment_Score__c, Batch_Processed__c, Conversation_Transcript_Body__c, Customer_Sentiments__c, CallDisposition from VoiceCall where RelatedRecordId != null and CallEndDateTime!= null AND CallDisposition=\'completed\' AND Customer_Sentiment_Score__c =null AND Batch_Processed__c = false and CreatedDate >= YESTERDAY' ;
        // retruning all VoiceCall data where CallEndDateTime!= null and sentiment score is not calculated
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<VoiceCall> scope) {
        
    try{
      List<VoiceCall> vcList = new List<VoiceCall>(); 
      RS_Einstein_Sentiment_Settings__mdt Sentisettings = RS_Einstein_Sentiment_Settings__mdt.getInstance('X1');
      List<Vision.Prediction> predictInstance;
      //Access token
      RS_PredictionController PredCont = new RS_PredictionController();
      String access_token = PredCont.getAccessToken();
      
          
        for(VoiceCall vc :scope){
            
            if(vc.VendorCallKey!=null){
               
                String conv = getData(vc.VendorCallKey);
                if(conv!=''){
                    vc.Batch_Processed__c = true;
                    vc.Conversation_Transcript_Body__c = conv;
                    //Sentiment section
                    predictInstance = new List<Vision.Prediction>();
                    predictInstance = Vision.predictSentiment(conv,access_token,Sentisettings.Model__c);
                    if((!predictInstance.isempty()) && predictInstance[0].probability != null){
                        vc.Customer_Sentiment_Score__c = predictInstance[0].probability;
                        vc.Customer_Sentiments__c = predictInstance[0].Label;
                    }
                    vcList.add(vc);
                }
            }
            
        }
        if(!vcList.isempty()){
            Database.update(vcList, false);
            list<Sentiment_Score__c> listSenticoreVC = new list<Sentiment_Score__c>();
            for(VoiceCall vc: vcList){
                Sentiment_Score__c sentiObj = new Sentiment_Score__c();
                sentiObj.Case__c = vc.RelatedRecordId;
                sentiObj.Customer_Sentiment_Score__c = vc.Customer_Sentiment_Score__c;
                sentiObj.Customer_Sentiments__c = vc.Customer_Sentiments__c;
                sentiObj.Conversation_Channel__c ='Voice Call';
                sentiObj.Voice_Call__c = vc.id;
                listSenticoreVC.add(sentiObj);  
            }
            if(!listSenticoreVC.isempty()){
                database.insert(listSenticoreVC,false);
            }
       }
  
    }catch(Exception e){
            system.debug('Exception Message>>>>>' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :bc.getJobId()]; 
    }
    //Method to get data for voice call/de726b34-4f1f-45e3-848a-23ba351c32f7
    public static String getData(String vendorCallKey){
        String conv='';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:SalesforceOrg/services/data/v53.0/connect/Conversation/'+vendorCallKey+'/entries');
        request.setMethod('GET');
        try{
            //request.setHeader('Authorization', 'Bearer '+UserInfo.getSessionId());
            HttpResponse response = http.send(request);
            if(response.getStatus()=='OK' && response.getBody()!=null){
                Rs_voiceCallParser vc = Rs_voiceCallParser.parse(response.getBody());
                for(Rs_voiceCallParser.cls_conversationEntries ce: vc.conversationEntries){
                    if(ce.messageText!=null){
                        conv = conv+ ce.messageText + '  ';
                    }
                }
            }
            return conv;
        }catch(exception a){
            return null;
        }
    }
}