force-app/main/default/objects/rS_Dynamic_Datatable__mdt/rS_Dynamic_Datatable__mdt.object-meta.xml
<CustomObject>
    <label>rS_Dynamic Datatable</label>
    <pluralLabel>rS_Dynamic Datatables</pluralLabel>
</CustomObject>

force-app/main/default/objects/rS_Dynamic_Datatable__mdt/fields/ObjectAPI_Name__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI_Name__c</fullName>
    <inlineHelpText>API name of the object.</inlineHelpText>
    <label>ObjectAPI Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/rS_Dynamic_Datatable__mdt/fields/RS_LastNDays__c.field-meta.xml
<CustomField>
    <fullName>RS_LastNDays__c</fullName>
    <label>LastNDays</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/RS_Account__c.field-meta.xml
<CustomField>
    <fullName>RS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RS_CustomerProfileChartController.cls
/**
* @description       : Custom controller for RS_CustomerProfileRelatedList
* @author            : Accenture
* @group             : 
* @last modified on  : 03-13-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

public with sharing class RS_CustomerProfileChartController {
    
        /**
	* @description 
	* @author  Accenture| 07-13-2022 
	* @param accountId : Corresponding AccountId
	* @param tabDetails
	* @return   List<AggregateResult>
	**/
    
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getAggregateRecordsByAccountId(String accountId, String tabDetails){
        String strWhereCondition='';
        List<rS_Dynamic_Datatable__mdt> dataTableMetaData = getObjectDetails(tabDetails);
        String recAccountId=String.escapeSingleQuotes(accountId);
        String strTabName = JSON.serialize(dataTableMetaData.get(0).get('DeveloperName'));
        String strTabNameFinal = strTabName.substringAfter('_');
        strTabNameFinal = strTabNameFinal.replace('_', ' ');
        strTabNameFinal = strTabNameFinal.replace('"', '');
         if(strTabNameFinal == 'Account Information'){
            strTabNameFinal = 'Account Information Update';
        }
        if(strTabNameFinal == 'Incorrect Invoice'){
            strTabNameFinal = 'Incorrect Invoicing';
        }


        
        if(dataTableMetaData.get(0).get('ObjectAPI_Name__c') == 'EmailMessage'){
            strWhereCondition = ' where Parent.Account.id= ';
        } else if(dataTableMetaData.get(0).get('ObjectAPI_Name__c') == 'LiveChatTranscript'){ 
            strWhereCondition = ' where Case.Account.id= ';
        }else if(dataTableMetaData.get(0).get('ObjectAPI_Name__c') == 'AssignedResource') {
             if(tabDetails.substringAfter(':')=='SME_Assistance' || tabDetails.substringAfter(':')=='Incorrect_Invoice' || tabDetails.substringAfter(':')=='Renewals'){
                strWhereCondition = ' where ServiceAppointment.WorkType.Name= '+ '\'' + strTabNameFinal + '\'' +' and ServiceAppointment.RS_Account__c= ';
            }else if(tabDetails.substringAfter(':')=='Upcoming_Appointments'){
                strWhereCondition = ' where ServiceAppointment.Status= '+ '\'' + 'Scheduled' + '\'' +' and ServiceAppointment.RS_Account__c= ';
            }else if(tabDetails.substringAfter(':')=='Past_Appointments'){
                strWhereCondition = ' where ServiceAppointment.Status= '+ '\'' + 'Closed' + '\'' +' and ServiceAppointment.RS_Account__c= ';
            }
            else{
               strWhereCondition = ' where ServiceAppointment.RS_Account__c= ';
            }
             
        } else if(dataTableMetaData.get(0).get('ObjectAPI_Name__c') == 'Case'){   // case records handling
            if(tabDetails.substringAfter(':')<>'All_Cases'){
                strWhereCondition = ' where type= '+ '\'' + strTabNameFinal + '\'' +' and Account.id= ';
            } else{
                strWhereCondition = ' where Account.id= ';
            }
        } else {
            strWhereCondition = ' where Related_Account__r.id= ';            
        }
       String dataTableObjectName=String.escapeSingleQuotes(String.valueOf((dataTableMetaData.get(0).get('ObjectAPI_Name__c'))));
       String dataTableLimit=String.escapeSingleQuotes(String.valueOf((dataTableMetaData.get(0).get('RS_LastNDays__c'))));
        String strSOQL = 'SELECT DAY_ONLY(CreatedDate) CRDATE,Count(id) Total from ' + dataTableObjectName + strWhereCondition + '\'' + recAccountId + '\'' + ' and CreatedDate = LAST_N_DAYS: ' +  dataTableLimit  + ' group by DAY_ONLY(CreatedDate) order by DAY_ONLY(CreatedDate)';
        
        List<AggregateResult> aggregateRecords =  Database.query(strSOQL);
        return aggregateRecords;
    }
    
            /**
	* @description 
	* @author  Accenture| 07-13-2022 
	* @param tabObjectDetails
	* @return  List<rS_Dynamic_Datatable__mdt>
	**/

    @AuraEnabled
    public static List<rS_Dynamic_Datatable__mdt> getObjectDetails(String tabObjectDetails){
        
        String sObjectString = String.escapeSingleQuotes('rS_Dynamic_Datatable__mdt'); // Metadata object name for configuration
        String fieldString = String.escapeSingleQuotes('ObjectAPI_Name__c,RS_LastNDays__c,DeveloperName '); // Selected aggregated query details 
        String strwhereConidtion = String.escapeSingleQuotes('  where MasterLabel=');
        String strMasterLabel = String.escapeSingleQuotes(tabObjectDetails);
        String strSOQL = 'SELECT ' + fieldString + ' FROM ' + sObjectString + strwhereConidtion + '\'' + strMasterLabel + '\'';
        List<rS_Dynamic_Datatable__mdt> dataTableMetaData = Database.query(strSOQL);
        return dataTableMetaData;
    }
}