force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/RS_Einstein_Sentiment_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>RS Einstein Sentiment Configuration</label>
    <pluralLabel>RS Einstein Sentiment Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Case_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Field_Name__c</fullName>
    <label>Case Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Customer_sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_sentiments__c</fullName>
    <label>Customer sentiments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Interaction_Lookup_Field__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Lookup_Field__c</fullName>
    <label>Interaction Lookup Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Interaction_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Object_API__c</fullName>
    <label>Interaction Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Sentiment_Field_to_analyse__c.field-meta.xml
<CustomField>
    <fullName>Sentiment_Field_to_analyse__c</fullName>
    <label>Sentiment Field to analyse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Configuration__mdt/fields/Sentiment_score_field_to_Update__c.field-meta.xml
<CustomField>
    <fullName>Sentiment_score_field_to_Update__c</fullName>
    <label>Sentiment score field to Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_Einstein_Sentiment_Settings__mdt/RS_Einstein_Sentiment_Settings__mdt.object-meta.xml
<CustomObject>
    <label>RS Einstein Sentiment Settings</label>
    <pluralLabel>RS Einstein Sentiment Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/Sentiment_Score__c.object-meta.xml
<CustomObject>
    <label>Sentiment Score</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sentiment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Conversation_Channel__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Channel__c</fullName>
    <label>Conversation Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voice Call</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Live Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <inlineHelpText>Gives Probability of Customer Sentiment</inlineHelpText>
    <label>Sentiment Probability Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiments__c</fullName>
    <label>Customer Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RS_SentimentCalculator.cls
/**
* @description       : This class is used to calculate sentiments on all the interactions with the customer from all the channels 
* @author            : Accenture
* @last modified on  : 04-04-2022
* @last modified by  : Accenture
**/
public class RS_SentimentCalculator {
    
    @future(callout=true)
    public static void getSentiment(String ChannelName, String InteractionId){
        Sobject sobj;
        String interactionSql;
        Vision.Prediction retSentiment = new Vision.Prediction();
        RS_PredictionController PredCont = new RS_PredictionController();
        try{
            if(ChannelName!=null && InteractionId!=null){
                RS_Einstein_Sentiment_Configuration__mdt mcs = RS_Einstein_Sentiment_Configuration__mdt.getInstance(ChannelName);
                RS_Einstein_Sentiment_Settings__mdt Sentisettings = RS_Einstein_Sentiment_Settings__mdt.getInstance('X1');
                
                if(mcs.Sentiment_Field_to_analyse__c!=null && mcs.Sentiment_score_field_to_Update__c!=null){
                    interactionSql  = 'Select id, '+ String.escapeSingleQuotes(mcs.Case_Field_Name__c)  + ',' + String.escapeSingleQuotes(mcs.Sentiment_Field_to_analyse__c) + ','+ String.escapeSingleQuotes(mcs.Sentiment_score_field_to_Update__c) + ','+ String.escapeSingleQuotes(mcs.Customer_sentiments__c);
                    interactionSql+= ' from '+ String.escapeSingleQuotes(mcs.Interaction_Object_API__c) + ' where id =:InteractionId';
                    sobj = Database.query(interactionSql); 
                }
                if(sobj!=null){
					String access_token = PredCont.getAccessToken();
					
					if((String)sobj.get(mcs.Sentiment_Field_to_analyse__c)!=null && access_token!=null){
						List<Vision.Prediction> predictInstance = new List<Vision.Prediction>();
						predictInstance = Vision.predictSentiment((String)sobj.get(mcs.Sentiment_Field_to_analyse__c) ,access_token,Sentisettings.Model__c);
						if(predictInstance !=null && predictInstance.size()>0){
							retSentiment= predictInstance[0];
						}
					}
					
					IF(retSentiment!=null){
						sobj.put(mcs.Sentiment_score_field_to_Update__c, retSentiment.probability);
						sobj.put(mcs.Customer_sentiments__c, retSentiment.label);
					}
					if(Schema.getGlobalDescribe().get(mcs.Interaction_Object_API__c).getDescribe().isUpdateable()) {
						update sobj; 
					}
					Sentiment_Score__c sentiObj = new Sentiment_Score__c();
						sentiObj.Case__c = (String)sobj.get(mcs.Case_Field_Name__c);
						sentiObj.Customer_Sentiment_Score__c = (Decimal)sobj.get(mcs.Sentiment_score_field_to_Update__c);
						sentiObj.Customer_Sentiments__c = (String)sobj.get(mcs.Customer_sentiments__c);
						sentiObj.Conversation_Channel__c = mcs.Label;
						if(mcs.Interaction_Lookup_Field__c!=null){
							sentiObj.put(mcs.Interaction_Lookup_Field__c,InteractionId);
						}
						if(Schema.getGlobalDescribe().get('Sentiment_Score__c').getDescribe().isCreateable()) {
							insert sentiObj;
						}
				}
            }
        }
        catch(Exception e){
            system.debug('ERROR >>>>>' + e.getMessage());
        } 
        
        
    }
}