force-app/main/default/objects/BestTimeToCall__x/BestTimeToCall__x.object-meta.xml
<CustomObject>
    <externalDataSource>BestTimeToCall</externalDataSource>
    <externalName>BestTimeToCall_R4Demo</externalName>
    <label>BestTimeToCall</label>
    <pluralLabel>BestTimeToCalls</pluralLabel>
</CustomObject>

force-app/main/default/objects/BestTimeToCall__x/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/IssueType__c.field-meta.xml
<CustomField>
    <fullName>IssueType__c</fullName>
    <label>IssueType</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MockInterface_Test.cls
@isTest
public class MockInterface_Test {
    
     @isTest
    static void passThroughtest(){
         List<BestTimeToCall__x> bestTimeToCallList = new List<BestTimeToCall__x>();

    BestTimeToCall__x bestTimeToCall = new BestTimeToCall__x(AccountNumber__c = '111237',IssueType__c = 'Billing',Month__c = 'March');

    bestTimeToCallList.add(bestTimeToCall);

    ObjectManager.setMock(new MockInterfaceOverride(bestTimeToCallList));

    Test.startTest();
        MockInterface mock1 = new MockInterface();
            mock1.passThrough(bestTimeToCallList);
         Test.stopTest();
    }

}