force-app/main/default/objects/BestTimeToCall__x/BestTimeToCall__x.object-meta.xml
<CustomObject>
    <externalDataSource>BestTimeToCall</externalDataSource>
    <externalName>BestTimeToCall_R4Demo</externalName>
    <label>BestTimeToCall</label>
    <pluralLabel>BestTimeToCalls</pluralLabel>
</CustomObject>

force-app/main/default/objects/BestTimeToCall__x/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/IssueType__c.field-meta.xml
<CustomField>
    <fullName>IssueType__c</fullName>
    <label>IssueType</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Next_Best_Action__mdt/Next_Best_Action__mdt.object-meta.xml
<CustomObject>
    <label>Best Time to Call</label>
    <pluralLabel>Best Time to Calls</pluralLabel>
</CustomObject>

force-app/main/default/objects/Next_Best_Action__mdt/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
                <default>true</default>
                <label>January</label>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RS_BestTimeToCallController_Test.cls
/**
* @description       : Test Class for RS_BestTimeToCallController ApexClass. 
* @author            : Accenture
* @last modified on  : 03-23-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class RS_BestTimeToCallController_Test {
    @TestSetup
    public static void createTestData(){
        User getuser=TestDataFactory.createUser();
    }
    @isTest
    static void getbesttimecalldetailstest(){
        Next_Best_Action__mdt myNBA = new Next_Best_Action__mdt(MasterLabel = 'BTTC_List');
        User u=[Select id from user limit 1];
        String accountreordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
      	Account getacoountdetails=TestDataFactory.accList();
        List<BestTimeToCall__x> bestTimeToCallList = new List<BestTimeToCall__x>();
        BestTimeToCall__x bestTimeToCall = new BestTimeToCall__x(AccountNumber__c = '111237',IssueType__c = 'Billing',Month__c = 'March');
        bestTimeToCallList.add(bestTimeToCall);
        ObjectManager.setMock(new MockInterfaceOverride(bestTimeToCallList));
        System.runAs(u) {
        Test.startTest();
        RS_BestTimeToCallController.getbesttimecalldetails(getacoountdetails.AccountNumber,bestTimeToCallList[0].IssueType__c,bestTimeToCallList[0].Month__c);
        RS_BestTimeToCallController.getBTTCmetaDetail();
        RS_BestTimeToCallController.getPicklistValuesForMonth();
        RS_BestTimeToCallController.getPicklistValuesForIssueType();
        RS_BestTimeToCallController.getWrapperOfSObjectFieldColumnActionValues(myNBA.MasterLabel,getacoountdetails.Id,bestTimeToCallList[0].IssueType__c,bestTimeToCallList[0].Month__c);
        Test.stopTest();
          }
        System.assertEquals('111237',bestTimeToCall.AccountNumber__c);
    }
    
}