force-app/main/default/objects/BestTimeToCall__x/BestTimeToCall__x.object-meta.xml
<CustomObject>
    <externalDataSource>BestTimeToCall</externalDataSource>
    <externalName>BestTimeToCall_R4Demo</externalName>
    <label>BestTimeToCall</label>
    <pluralLabel>BestTimeToCalls</pluralLabel>
</CustomObject>

force-app/main/default/objects/BestTimeToCall__x/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/Afternoon__c.field-meta.xml
<CustomField>
    <fullName>Afternoon__c</fullName>
    <label>Afternoon</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/DayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>DayOfWeek__c</fullName>
    <label>DayOfWeek</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/Evening__c.field-meta.xml
<CustomField>
    <fullName>Evening__c</fullName>
    <label>Evening</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/IssueType__c.field-meta.xml
<CustomField>
    <fullName>IssueType__c</fullName>
    <label>IssueType</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BestTimeToCall__x/fields/Morning__c.field-meta.xml
<CustomField>
    <fullName>Morning__c</fullName>
    <label>Morning</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Next_Best_Action__mdt/Next_Best_Action__mdt.object-meta.xml
<CustomObject>
    <label>Best Time to Call</label>
    <pluralLabel>Best Time to Calls</pluralLabel>
</CustomObject>

force-app/main/default/objects/Next_Best_Action__mdt/fields/CaseIssueType__c.field-meta.xml
<CustomField>
    <fullName>CaseIssueType__c</fullName>
    <label>CaseIssueType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing</fullName>
                <default>true</default>
                <label>Billing</label>
            </value>
            <value>
                <fullName>Policy</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
            <value>
                <fullName>Account Information Update</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
                <isActive>false</isActive>
                <label>Complaint</label>
            </value>
            <value>
                <fullName>Maintenance Inquiry</fullName>
                <isActive>false</isActive>
                <label>Maintenance Inquiry</label>
            </value>
            <value>
                <fullName>Order Inquiry</fullName>
                <isActive>false</isActive>
                <label>Order Inquiry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Next_Best_Action__mdt/fields/Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Header_Value__c</fullName>
    <label>Header Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Next_Best_Action__mdt/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
                <default>true</default>
                <label>January</label>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Next_Best_Action__mdt/fields/ObjectAPI_Name__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI_Name__c</fullName>
    <label>ObjectAPI Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RIS_BTTC_TimeSlots_Dev__x/RIS_BTTC_TimeSlots_Dev__x.object-meta.xml
<CustomObject>
    <externalDataSource>BestTimeToCall</externalDataSource>
    <externalName>BTTC-TimeSlots_R4Demo</externalName>
    <label>RISBTTCTimeSlotsDev</label>
    <pluralLabel>RISBTTCTimeSlotsDevs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RIS_BTTC_TimeSlots_Dev__x/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>EndTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RIS_BTTC_TimeSlots_Dev__x/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RIS_BTTC_TimeSlots_Dev__x/fields/SlotName__c.field-meta.xml
<CustomField>
    <fullName>SlotName__c</fullName>
    <label>SlotName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RIS_BTTC_TimeSlots_Dev__x/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RS_BestTimeToCallController.cls
/**
* @description       : Controller Class for rS_BestTimeToCall LWC. 
* @author            : Accenture
* @last modified on  : 03-23-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with Sharing class RS_BestTimeToCallController {
    
/**
* @description : Get Meta Records
* @author  Accenture| 03-08-2023
* @param accountId : Customer AccountId
* @param issueType : Case Issue Type
* @param month     : Month 
* @return   List<BestTimeToCall__x>  : retruns the list of BestTimeToCall__x based on input params
**/
    @AuraEnabled
    public static  List<BestTimeToCall__x> getbesttimecalldetails(String accountId,String issueType,String month){
        Map<String,BestTimeToCall__x> details=new  Map<String,BestTimeToCall__x>();
        String accountnumber=[Select AccountNumber from Account where id=:accountId]?.AccountNumber;
        List<BestTimeToCall__x> getdetails= ObjectManager.records([Select Afternoon__c,Morning__c,Evening__c,DayOfWeek__c from BestTimeToCall__x 
                                                                   where Month__c=:month and IssueType__c =:issueType and AccountNumber__c=:accountnumber]);
        return getdetails;
    }
    /**
* @description : Get Meta Records 
* @author  Accenture| 03-08-2023
* @return   List<Next_Best_Action__mdt>  : retruns the list of Next_Best_Action__mdt records
**/
    @AuraEnabled
    public static  List<Next_Best_Action__mdt> getBTTCmetaDetail(){
        
        List<Next_Best_Action__mdt> bttcMdt = Next_Best_Action__mdt.getAll().values();
        return bttcMdt;
    }
    @AuraEnabled(cacheable=true)
    public static DataTableResponse getWrapperOfSObjectFieldColumnActionValues(String tableName,String accountId,String issueType,String month)
    {
        List<DataTableColumns> lstDataColumns            = new List<DataTableColumns>();
        List<SObject> lstDataTableData                   = new List<SObject>();
        List<string> columnList                          = new List<string>();
        List<string> fieldAPINameList                    = new List<string>();
        String strRecordId;
        String query;
        List<string> headerValuesList                    = new List<string>();
        Next_Best_Action__mdt tableComponentMetadata = [SELECT Id, DeveloperName, Field_Value__c,Header_Value__c,ObjectAPI_Name__c,Month__c,CaseIssueType__c, Limit__c FROM Next_Best_Action__mdt WHERE DeveloperName =: tableName WITH SECURITY_ENFORCED];
        list<RIS_BTTC_TimeSlots_Dev__x> listtimeSlot = [select Id__c,SlotName__c,StartTime__c,EndTime__c from RIS_BTTC_TimeSlots_Dev__x WITH SECURITY_ENFORCED];
        if(tableComponentMetadata.Header_Value__c != null)
        {
            headerValuesList = tableComponentMetadata.Header_Value__c.split(',');
        }
        columnList.add(month);
        for(integer j = listtimeSlot.size(); j > 0; j--){
            String valuetoadd=listtimeSlot[j-1].SlotName__c+ '\n' +'('+listtimeSlot[j-1].StartTime__c+' '+'-'+' '+listtimeSlot[j-1].EndTime__c+')';
            columnList.add(valuetoadd);
        }
        if(tableComponentMetadata.Field_Value__c != null)
        {
            fieldAPINameList = tableComponentMetadata.Field_Value__c.split(',');
        }
        String fields = String.join(fieldAPINameList,',');
        for(integer i = 0; i < columnList.size(); i++)
        {
            
            DataTableColumns datacolumns = new DataTableColumns( columnList[i].trim() , 
                                                                fieldAPINameList[i].substringBefore(':').trim(), 
                                                                fieldAPINameList[i].substringAfter(':').trim());
            
            lstDataColumns.add(datacolumns);
        }
        String accountnumber=[Select AccountNumber from Account where id=:accountId]?.AccountNumber;
        String tableComponentObjectName=String.escapeSingleQuotes(tableComponentMetadata.ObjectAPI_Name__c);
        String tableComponentLimit=String.escapeSingleQuotes(tableComponentMetadata.Limit__c);
        if(accountnumber != null){
           // query = 'Select ' +  fields  + ' FROM ' + tableComponentObjectName; 
        
        
        //String a = 'Select ' +  fields  + ' FROM ' + tableComponentObjectName +' where AccountNumber__c = '+ +'\''+ accountnumber +'\''+' and '+' Month__c = '+ +'\''+ month +'\''+' and '+' IssueType__c = '+ +'\''+ issueType +'\''+' Limit '+ tableComponentLimit ;
        for(SObject sObjectItem : Database.query('Select ' +  String.escapeSingleQuotes(fields)  + ' FROM ' + String.escapeSingleQuotes(tableComponentObjectName) +' where AccountNumber__c = '+ +'\''+ String.escapeSingleQuotes(accountnumber) +'\''+' and '+' Month__c = '+ +'\''+ String.escapeSingleQuotes(month) +'\''+' and '+' IssueType__c = '+ +'\''+ String.escapeSingleQuotes(issueType) +'\''+' Limit '+ String.escapeSingleQuotes(tableComponentLimit)))
        {
            lstDataTableData.add(sObjectItem);
        }
    }
        DataTableResponse finalWrapper   = new DataTableResponse();
        finalWrapper.lstDataTableColumns = lstDataColumns;
        finalWrapper.lstDataTableData    = lstDataTableData;
        return finalWrapper;
        
    }
           /**
* @description       : Inner Wrapper Class 
* @author            : Accenture
* @group             : 
* @last modified on  : 03-23-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
    
    public class DataTableColumns {
        /**
* @description       : Datatable Label
**/
        @AuraEnabled
        public String label {get;set;}
/**
* @description       : FieldName
**/
        @AuraEnabled       
        public String fieldName {get;set;}
         /*Case Issue Type Lable*/
        @AuraEnabled
        public String type {get;set;}
        
        /**
        * @description 
        * @author ChangeMeIn@UserSettingsUnder.SFDoc | 03-09-2023 
        * @param label 
        * @param fieldName 
        * @param type 
        **/
        public DataTableColumns(String label, String fieldName, String type)
        {
            this.label     = label;
            this.fieldName = fieldName;
            this.type      = type;          
        }
    }
               /**
* @description       : Inner Wrapper Class to Return Output
**/
    public class DataTableResponse {
        @AuraEnabled
        public List<DataTableColumns> lstDataTableColumns {get;set;}
        @AuraEnabled
        public List<sObject> lstDataTableData {get;set;}     
    }
/**
* @description : Get List of Months
* @author  Accenture| 03-08-2023
* @return   List<String>  : retruns the list of Month Names
**/
    @AuraEnabled(cacheable=true)
    public static List<String> getPicklistValuesForMonth(){
        List<String> pickListValues = new List<String>();
        Schema.DescribeFieldResult pickList = Next_Best_Action__mdt.Month__c.getDescribe();
        for( Schema.PicklistEntry pickVal : pickList.getPicklistValues()){
            pickListValues.add(pickVal.getValue());
        }   
        return pickListValues;
    }

        /**
* @description : Get Case Type Picklist Values
* @author  Accenture| 03-08-2023
* @return   List<String>  : retruns the list of Case Issue Types Names
**/
    @AuraEnabled(cacheable=true)
    public static List<String> getPicklistValuesForIssueType(){
        List<String> pickListValues = new List<String>();
        Schema.DescribeFieldResult pickList = Next_Best_Action__mdt.CaseIssueType__c.getDescribe();
        for( Schema.PicklistEntry pickVal : pickList.getPicklistValues()){
            
            pickListValues.add(pickVal.getValue());
        }   
        return pickListValues;
    }
    
}