force-app/main/default/objects/VoiceCall/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Voice Calls</relationshipLabel>
    <relationshipName>Voice_Calls_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_ContactId__c.field-meta.xml
<CustomField>
    <fullName>RS_ContactId__c</fullName>
    <label>ContactId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_Customer_Identified__c.field-meta.xml
<CustomField>
    <fullName>RS_Customer_Identified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Identified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_CustomerAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>RS_CustomerAccountNumber__c</fullName>
    <label>Social Security Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_CustomerVerified__c.field-meta.xml
<CustomField>
    <fullName>RS_CustomerVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>RS_DateOfBirth__c</fullName>
    <label>DateOfBirth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_Switch_To_SMS__c.field-meta.xml
<CustomField>
    <fullName>RS_Switch_To_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag will be enabled if customer has switched from IVR to SMS.</description>
    <label>Switch To SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/RS_Switching_Status__c.field-meta.xml
<CustomField>
    <fullName>RS_Switching_Status__c</fullName>
    <label>Switching Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RS_vc_aws_sync_test.cls
/**
* @description       : Test Class for RS_vc_aws_sync ApexClass
* @author            : Accenture
* @group             : 
* @last modified on  : 03-24-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class RS_vc_aws_sync_test{
	
    @isTest
     public static void testMethod1(){
        VoiceCall vcobj = TestDataFactory.VCList(True);
        RS_vc_aws_sync.updateCustomerInfo(vcObj.RS_ContactId__c, vcObj.RS_CustomerAccountNumber__c, vcObj.RS_CustomerVerified__c, vcObj.RS_Customer_Identified__c, vcObj.Related_Account__c, vcObj.RS_DateOfBirth__c,vcObj.RS_Switch_To_SMS__c,vcObj.RS_Switching_Status__c);
        System.assertEquals(false,String.isempty(vcobj.id));
      }
}