force-app/main/default/objects/Account/fields/High_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>High_End_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High-End Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Retention_Risk__c.field-meta.xml
<CustomField>
    <fullName>Retention_Risk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retention Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Recovery__c.field-meta.xml
<CustomField>
    <fullName>Service_Recovery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Recovery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Billing.recordType-meta.xml
<RecordType>
    <fullName>Billing</fullName>
    <active>true</active>
    <businessProcess>Case  Support Process</businessProcess>
    <label>Billing</label>
</RecordType>

force-app/main/default/objects/Sentiment_Score__c/Sentiment_Score__c.object-meta.xml
<CustomObject>
    <label>Sentiment Score</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sentiment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <inlineHelpText>Gives Probability of Customer Sentiment</inlineHelpText>
    <label>Sentiment Probability Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiments__c</fullName>
    <label>Customer Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RS_unmarkRetentionCustomerBatch_Test.cls
/**
 * @description       : Test Class for RS_unmarkRetentionCustomerBatch
 * @author            : Accenture
 * @group             : 
 * @last modified on  : 03-24-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public class RS_unmarkRetentionCustomerBatch_Test {
    @IsTest
    static void exceuteBatchTest(){
        RS_unmarkRetentionCustomerBatch rsobj = new RS_unmarkRetentionCustomerBatch();
        List<Account> acList = new List<Account>();
        Account acc=TestDataFactory.accList();
        acc.High_End_Customer__c=true;
        acc.Service_Recovery__c=true;
        acList.add(acc);
        update acList;
        Case c;
        List<Case> cslist = new List<Case>();
            c = TestDataFactory.csList();
            c.AccountId=acc.id;
        	c.Type = 'Billing';
            cslist.add(c);
        update cslist;
        System.assertEquals('Billing',c.Type);
        List<Sentiment_Score__c> sclist= new List<Sentiment_Score__c>();
                Sentiment_Score__c  sc = new Sentiment_Score__c();
                sc.Customer_Sentiments__c ='Positive';
                sc.Case__c=c.id;
                sc.Customer_Sentiment_Score__c = 0.75;
                sclist.add(sc);
        insert sclist;
        DataBase.executebatch(rsobj);
        
    }
        
    @istest
    static void excecutetest2(){
        RS_unmarkRetentionCustomerBatch rsobj = new RS_unmarkRetentionCustomerBatch();
        Account a=TestDataFactory.accList();
        a.Retention_Risk__c=true;
        a.Service_Recovery__c=true;
        update a;
        Case c = new Case();
        Sentiment_Score__c  sc = new Sentiment_Score__c();
        List<Case> cslist = new List<Case>();
        List<Sentiment_Score__c> scList = new List<Sentiment_Score__c>();
            c= TestDataFactory.csList();
            c.AccountId=a.id;
            cslist.add(c);
            sc.Customer_Sentiments__c ='Negative';
        	sc.Case__c=c.id;
        	sc.Customer_Sentiment_Score__c = 0.75;
            scList.add(sc);
        update cslist;
        System.assertEquals('Negative',sc.Customer_Sentiments__c);
        insert sc;
        Integer negativeSentimentDays =-1;
        Integer repeatedDays =0;
        Integer noofRepeatedCase=0;
        DataBase.executebatch(rsobj);
    }
    
   
    
}