force-app/main/default/objects/Account/fields/High_End_Customer__c.field-meta.xml
<CustomField>
    <fullName>High_End_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High-End Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Retention_Risk__c.field-meta.xml
<CustomField>
    <fullName>Retention_Risk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retention Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/No_of_Negative_Sentiments__c.field-meta.xml
<CustomField>
    <fullName>No_of_Negative_Sentiments__c</fullName>
    <label># of Negative Sentiments</label>
    <summaryFilterItems>
        <field>Sentiment_Score__c.Customer_Sentiments__c</field>
        <operation>equals</operation>
        <value>Negative</value>
    </summaryFilterItems>
    <summaryForeignKey>Sentiment_Score__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/Sentiment_Score__c.object-meta.xml
<CustomObject>
    <label>Sentiment Score</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sentiment Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sentiment_Score__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Sentiment Scores</relationshipLabel>
    <relationshipName>Sentiment_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiment_Score__c</fullName>
    <inlineHelpText>Gives Probability of Customer Sentiment</inlineHelpText>
    <label>Sentiment Probability Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentiment_Score__c/fields/Customer_Sentiments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sentiments__c</fullName>
    <label>Customer Sentiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RS_markRetentionCustomerBatch_Testclass.cls
@istest
public class RS_markRetentionCustomerBatch_Testclass {
    @istest
    static void excecuteBatchTest(){
        RS_markRetentionCustomerBatch rsobj = new RS_markRetentionCustomerBatch();
        List<Account> acList = new List<Account>();
        Account acc=TestDataFactory.accList();
        system.assertEquals(false,String.isEmpty(acc.id));
        acc.High_End_Customer__c=true;
        acList.add(acc);
        update acList;
        
        Case cobj;
        List<Case> cslist = new List<Case>();
        for(Integer i =0;i<=10;i++){
            cobj= TestDataFactory.csList();
            cobj.AccountId=acc.id;
            cslist.add(cobj);
            
        }
        update cslist;
        List<Sentiment_Score__c> sclist= new List<Sentiment_Score__c>();
        for(integer i = 0; i<=10; i++){
            for(Case cs:cslist){
                Sentiment_Score__c  sc = new Sentiment_Score__c();
                sc.Customer_Sentiments__c ='Negative';
                sc.Case__c=cs.id;
                sc.Customer_Sentiment_Score__c = 0.75;
                sclist.add(sc);
            }
        }
        insert sclist;
        Decimal countcase =[Select No_of_Negative_Sentiments__c from case where id=:cobj.id]?.No_of_Negative_Sentiments__c;
        
        //Integer NegativeSentimentDays =1;
        //Integer RepeatedDays =0;
        //Integer NoofRepeatedCase=0;
        DataBase.executebatch(rsobj);
    }
    
    @istest
    static void excecutetest2(){
        RS_markRetentionCustomerBatch rsobj = new RS_markRetentionCustomerBatch();
        Account a=TestDataFactory.accList();
        system.assertEquals(false,String.isEmpty(a.id));
        a.Retention_Risk__c=true;
        update a;
        Case c;
        List<Case> cs1 = new List<Case>();
        for(Integer i =0;i<=8;i++){
            c= TestDataFactory.csList();
            c.AccountId=a.id;
            cs1.add(c);
        }
        update cs1;
        
        Decimal countcase =[Select No_of_Negative_Sentiments__c from case where id=:c.id]?.No_of_Negative_Sentiments__c;
        Sentiment_Score__c  sc = new Sentiment_Score__c ();
        //sc.Customer_Sentiment__c ='Negative';
        sc.Case__c=c.id;
        insert sc;
        //Integer NegativeSentimentDays =-1;
        //Integer RepeatedDays =0;
        //Integer NoofRepeatedCase=0;
        DataBase.executebatch(rsobj);
    }
    
}