force-app/main/default/objects/Account/fields/RSI_Insurance_Agent__c.field-meta.xml
<CustomField>
    <fullName>RSI_Insurance_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/RSI_Name__c.field-meta.xml
<CustomField>
    <fullName>RSI_Name__c</fullName>
    <formula>FirstName  + &apos; &apos;  +  LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RSI_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RS_InsuranceDetailsPortalView.cls
/**
 * @description       : Controller for rsi_insuranceAgentDetailsOnPortal LWC
 * @author            : Accenture
 * @group             : 
 * @last modified on  : 03-24-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class RS_InsuranceDetailsPortalView {
    
    /**
    * @description 
    * @author Accenture | 03-13-2023 
    * @param userId 
    * @return List<User> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<User> getInsuranceAgentDetails(Id userId){
        User accountId=[SELECT Id,ContactId,Name,Email FROM User WHERE id=:userId WITH SECURITY_ENFORCED];
        String contactId=accountId.ContactId;
        if(contactId!=null){
        Contact con=[select AccountId,Id from contact where id=:contactId WITH SECURITY_ENFORCED];
        Account acc = [select RSI_Insurance_Agent__c,Id from Account where Id =:con.AccountId WITH SECURITY_ENFORCED];
        List<User> insuranceUserDetails=[select Id,Name,email,address,phone,RSI_Name__c,SmallPhotoUrl,FullPhotoUrl  from user where Id=:acc.RSI_Insurance_Agent__c WITH SECURITY_ENFORCED];
        return insuranceUserDetails;
        }
        return null;
    }

}