force-app/main/default/objects/RS_DynamicSearch__mdt/RS_DynamicSearch__mdt.object-meta.xml
<CustomObject>
    <label>RS_DynamicSearch</label>
    <pluralLabel>RS_DynamicSearch</pluralLabel>
</CustomObject>

force-app/main/default/objects/RS_DynamicSearch__mdt/fields/Lookup_Field_to_Link__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Field_to_Link__c</fullName>
    <label>Lookup Field to Link</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_DynamicSearch__mdt/fields/Update_Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Update_Case_Id__c</fullName>
    <label>Update Case Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RS_GuidedFlowConfScreenControllerTest.cls
/**
* @description       : Test class for RS_GuidedFlowConfScreenController
* @author            : joel.samuel.s.penke@accenture.com
* @group             : SF
* @last modified on  : 03-24-2023
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class RS_GuidedFlowConfScreenControllerTest {
    
    /**
    * @description : Test Data Setup
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 03-24-2023 
    **/
    @TestSetup
    public static void createCase(){
        User userTest=TestDataFactory.createUser();
    }
    
    @isTest
    public static void testConfirmationScreen(){
        Case createcase = TestDataFactory.CaseMethod(true);
        String choice = TestDataFactory.createAgentChoices();
        String caseId = ([SELECT Id from Case LIMIT 1]).Id;
        RS_DynamicSearch__mdt getmetaData=[select Object_Name__c,Lookup_Field_to_Link__c,Update_Case_Id__c from RS_DynamicSearch__mdt where label LIKE:'MessagingSession'  LIMIT 1];
        system.debug('getmetaData'+getmetaData);
        System.assertEquals(false,String.isEmpty(caseId));
        Test.startTest();
        User us = [Select id from user where LastName='Test' LIMIT 1];
        System.runAs(us){
            String getRecordTypeName=[Select DeveloperName from RecordType where SobjectType='Case' Limit 1]?.DeveloperName;
            RS_GuidedFlowConfScreenController.fetchFields('MessagingSession',getRecordTypeName);
            RS_GuidedFlowConfScreenController.getChoiceDetails(choice,createcase,'4',getRecordTypeName);
            RS_GuidedFlowConfScreenController.updateChoiceRecord(choice,getmetaData.Lookup_Field_to_Link__c,getmetaData.Update_Case_Id__c,caseId,caseId);
            RS_GuidedFlowConfScreenController.getCommunityURL(us.Id);
        }
        Test.stopTest();
        
    }
}