force-app/main/default/objects/RS_TabConfiguration__mdt/RS_TabConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>RS_TabConfiguration</label>
    <pluralLabel>RS_TabConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/RS_TabConfiguration__mdt/fields/Child_ComponentType__c.field-meta.xml
<CustomField>
    <fullName>Child_ComponentType__c</fullName>
    <label>Child ComponentType</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RS_TabConfiguration__mdt/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RS_DynamicTabSet.cls
/**
* @description       : Controller to fetch configuration and data for the Dynamic Tab Screen 
* @author            : joel.samuel.s.penke@accenture.com
* @group             : SF
* @last modified on  : 06-29-2022
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class RS_DynamicTabSet {
    
    /**
* @description 
* @author  Accenture| 07-13-2022 
* @param recordName : Corresponding AccountId
* @return   List<RS_TabConfiguration__mdt>
**/
    
    @AuraEnabled
    public static List<RS_TabConfiguration__mdt> fetchTabs(String recordName){
        List<RS_TabConfiguration__mdt> mdtList = new List<RS_TabConfiguration__mdt>();
        RS_TabConfiguration__mdt mdtRec  =new RS_TabConfiguration__mdt();
        try {
            if(String.isNotBlank(recordName)){
                if(Schema.getGlobalDescribe().get('RS_TabConfiguration__mdt').getDescribe().isAccessible()){
                    mdtRec = [SELECT MasterLabel,DeveloperName, Child_ComponentType__c, Order__c,Parent__c,Active__c, Sequence__c from   RS_TabConfiguration__mdt WHERE Parent__c =:recordName AND Active__c = true WITH SECURITY_ENFORCED ORDER BY Sequence__c ASC LIMIT 1 ];
                }
            }
            Decimal order = (mdtRec != null && mdtRec.Order__c != null && ! mdtRec.Parent__c.contains('Standard')) ? (mdtRec.Order__c) : 1; 
            if(Schema.getGlobalDescribe().get('RS_TabConfiguration__mdt').getDescribe().isAccessible()){
                mdtList = [SELECT MasterLabel,DeveloperName, Child_ComponentType__c, Order__c, Parent__c,Active__c,Sequence__c from  RS_TabConfiguration__mdt WHERE Order__c =:order AND Parent__c =:recordName AND Active__c = true WITH SECURITY_ENFORCED ORDER BY Sequence__c ASC];
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return mdtList;
    }
}